### ISSUE TITLE
トップページを作る

### ISSUE THREAD

**Issue by kou** [oss-gate/oss-gate.github.io#1]
「OSS Gate」と言ってURLで参照できるところがあった方が便利そうなので、トップページだけでも作るのはどうだろう。

http://www.clear-code.com/blog/2015/10/20.html にリンクを張るよりも https://oss-gate.github.io/ とかの方がよさそう。

**Comment by sezemiadmin** [comment]
もちろん、あったほうが良いと思うのですが、時間かかるかもしれないと思ったのですが、取り急ぎ、door keeper のページを少しだけ更新しました-> https://oss-gate.doorkeeper.jp/

**Comment by tdtds** [comment]
ちょっと手が空いたので、Jekyllの標準テンプレートを使って作っておきました。リポジトリにpush済み、 https://oss-gate.github.io/ でアクセスできます。フォーマットはMarkdownです。

**Comment by satoryu** [comment]
[![LGTM](http://lgtm.in/p/CbqeKakFn)](http://lgtm.in/i/CbqeKakFn)

**Comment by kou** [comment]
すごい！
