### ISSUE TITLE
OSS Gateに協力企業ページを作ってはどうか

### ISSUE THREAD

**Issue by ycatch** [oss-gate/oss-gate.github.io#22]
別ページで作ってみる。
そうすると、協力企業が直接リンクしやすい。

**Comment by ycatch** [comment]
サイトのリニューアルは、こっちでやった
https://github.com/oss-gate/retrospective/issues/29

**Comment by ycatch** [comment]
追加しました。
https://github.com/oss-gate/oss-gate.github.io/commit/5c2fb52cfea00d2c759d708f60c4eb3a2feb7acf

**Comment by ycatch** [comment]
掲載情報は、Doorkeeperの会場から拾いました。

**Comment by kou** [comment]
ありがとうございます！
思うところはあるんですが、時間がとれなくてコメントできていません！
来週のワークショップ中に時間を見つけてコメントしたいなぁと思っていました。。。

**Comment by knokmki612** [comment]
企業や団体のロゴを追加すると視覚的に分かりやすいと思いますが、追加する場合はロゴの使用許可や使用するデータの問い合わせが必要になりそうですね。

**Comment by kou** [comment]
協力する企業を増やしていきたい（直近だとDoorkeeprの利用料の協力とか。Doorkeeperを利用し続けるの？とかもあるけどそれはそれで別にして。）ので「たとえばこういう協力を求めています！」みたいなページも作りたいと思っていました！

**Comment by kou** [comment]
どんな感じで協力したか（会場提供とか、社員がOSS Gateに参加するときの交通費を支援とか）も書きたいと思っていました！

**Comment by kou** [comment]
「OSS開発に参加している人は歓迎です！」みたいな企業ならそういう情報も載せたいと思っていました！

**Comment by kou** [comment]
こんなイメージです！（伝わるといいな。。。）

* https://oss-gate.github.io/sponsors/
* https://oss-gate.github.io/sponsors/wanted.html

**Comment by knokmki612** [comment]
> https://oss-gate.github.io/sponsors/

それぞれの企業がどのような形で関わっているのかがとても分かりやすいですし、納得感があると思いました。

**Comment by hiroyuki-sato** [comment]
きっと須藤さんは会場提供協力企業募集みたいな文言を入れたいんだろうなと思ってました。:smile:

この間のイベント会場だと必要な設備はこんな感じですかね？
(なんか机・椅子の表現がイマイチですが、、)

* 時
  * 土曜日・日曜日: 午前10時から午後6時頃まで
  * 平日: 午後7時頃から午後10時頃まで
* 場所: 東京23区、札幌、大阪、名古屋...
* 収容人数: 10名 ~ 50名
* 机・椅子
  * 2名または4名が対面で座りPCを利用できる机が理想的です。
* 電源
* プロジェクタ・スクリーン
* 無線LAN
* インターネットアクセス
* 電源タップ(なければこちらで用意)
* マイク(もしあれば)

ちなみに電源タップは、うちの会社にあんまり使っていないのが10個ぐらいはあるので貸し出すことはできると思います。あ、でも大体4個口です。(持ってきてもらった方が楽ですけどね)

**Comment by ycatch** [comment]
なるほど。ちょっと作ってみますね。

**Comment by kou** [comment]
TODOがいろいろ残っていますが、 https://oss-gate.github.io/sponsors/ を公開しました！

**Comment by ycatch** [comment]
すっかり、ほったらかしてしまい、失礼しました。
ご苦労様でした。
