### ISSUE TITLE
「OSS Gate東京ワークショップ2017-01-28」のレポートをまとめる

### ISSUE THREAD

**Issue by kou** [oss-gate/oss-gate.github.io#26]
https://github.com/oss-gate/oss-gate.github.io/blob/master/workshop/report.md にまとめる。

**Comment by kou** [comment]
だれか、頼む。。。

**Comment by sezemiadmin** [comment]
やり方を壮大に間違えてしまっている感がありますが、、、↓にまとめました。。
https://github.com/oss-gate/oss-gate.github.io/pull/27

**Comment by kou** [comment]
カンペキです！と思ったのですが、「2017-01-28開催のワークショップ（東京）」のリンク先が違っていました＞＜

**Comment by sezemiadmin** [comment]
ぬを... :bowing_man: :

**Comment by sezemiadmin** [comment]
修正しました。。。 https://github.com/oss-gate/oss-gate.github.io/pull/28

**Comment by kou** [comment]
いえーい！
