### ISSUE TITLE
社内/学内OSS Gateワークショップの開催を呼びかけてみるのはどうか

### ISSUE THREAD

**Issue by sezemiadmin** [oss-gate/oss-gate.github.io#3]
企業内/学内の育成? 交流? OSS力up? などの目的で、OSS Gateワークショップをその企業内/学内で開くというのはどうでしょうか?
社内/学内だと参加ハードル下がるとかもありそうだし、その会社のエンジニアブログとかで拡散も期待できそう

## 概要
- OSS Gateから1回目だけ進行役がいく
- 企業内での事前準備は[ シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md) と [Doorkeeperの告知ページ](https://oss-gate.doorkeeper.jp/events/42159) を紹介し、オンラインで詰める
- OSS Gate から 次回メンターに来てね! とか参加したブログ書いてね、でも何でも良いのでPRや告知が出来るといいなぁ

**Comment by kou** [comment]
いいと思います！
ちなみに、私は、6/11（土）に企業向けにワークショップを実施する予定です。

**Comment by sezemiadmin** [comment]
おお! もう実施する運びなんですね!! スゴイ!
たまたま営業に伺った企業さんで聞いてみたところ、まだ、そんな雰囲気ではないみたいなゴニョゴニョとした感じで、ポジティブな印象では無かったんです。
というところで、その企業さんのモチベーションとか、詳しく聞いてみたいです!!

**Comment by kou** [comment]
開催レポートが今後活用できる…かもしれないですが、どうやったかにフォーカスしすぎている気がするので使いづらいかもしれませんね。。。
http://oss-gate.github.io/report/workshop/2016/06/11/workshop-report.html

**Comment by sezemiadmin** [comment]
おお! まとめ、ありがとうございます!! シナリオがアップデートされた感があって、分かりやすいですね!

とはいえ、おっしゃるとおり、なぜやったのかは、分からないですね。
メンターのアンケート結果で一部ありましたが、それが企業の意志とは言いがたい気がします。

ちなみに、今回の企業さんは継続して開催しよう、という気持ちにはなられたんですかね?
在籍しているエンジニアの人数に依存するとは思うのですが。

その一方で、このissueで発言される人がいないので、皆さん、あまりモチベーション無さそうかなぁ、と思い始めてます。

**Comment by y-goto** [comment]
弊社内でOSS Gateを実施してみようかと考えたことはあるのですが、結局他の形の講座（後述）にしましたね。OSS Gateを弊社でやるためには、以下をクリアする必要がありそうです。

1. 朝から一日OSS Gateのみで拘束してしまうので、参加者の負荷が大きく、会場の確保も大変。
2. メンターの数もビギナーの数に比例してかなり必要となり、人数を集めるのが大変。
3. 会社から外部に何か出す場合、公開するための会社の手続きが必要。海外にも出るので輸出審査とかがある。その場でOSSをパッと決めて何かを投稿するというわけにはいかない。
4. 弊社とは言いませんが、パッチを投稿するのに課長以上の偉い人のハンコが５つ必要とかの（馬鹿馬鹿しい）ルールを作っているケースがあって、そういう人たちに理解してもらうのが大変。

これらの問題をカバーできるという意味では、OpenStackユーザー会がやっているUpstream Training( http://www.atmarkit.co.jp/ait/articles/1410/27/news084.html ) のほうが楽なんです。こちらはレゴブロックを使って機能提案からマージに至るまでのシミュレーションを行う形式ですが、以下のようなメリットがあるのです。

1. 2時間程度で終わるので、参加者や会場の負担が少ない
2. メンターが4人程度で20人のビギナーでも大丈夫
3. レゴで建物を作るだけで、実際に何かを外に出すわけではないので、手続き不要。
4. 外に何も出さない以上、妙なルールや人にも縛られる恐れがない。

というわけで、このUpstream Training（＋私の講義）という形にしました。
OSS Gateにも実際に投稿を体験できるとか良いところもあるのですが、結局一長一短なんでしょうね。

**Comment by satoryu** [comment]
今回のレポートは、OSS Gateワークショップを運営する側が書いたので、どうやったかが重点的に書かれているのだと思います。
可能であれば、今回ワークショップをお願いした企業さんに、

* なぜワークショップをお願いしたか（企業内の背景）
* ワークショップ当日の雰囲気（ビギナー視点）
* ワークショップ後に企業内に起きたこと（変わったことやわかった課題など）

を書いてもらえると、企業内・学内で実施を検討している方が参考にしやすいのではないでしょうか。

**Comment by sezemiadmin** [comment]
@y-goto ありがとうございます!! 企業によって実施へのハードルが違うんですねぇ。。
そうすると積極的に "社内や学内でやりませんか?" と勧誘するより、oss-gate.github.io に社内で開催する効果や必要な情報を出して、興味をもった企業(実施したいモチベーションが高い = ハードルを乗り越えられそう)からの問合せを待つほうが良いと感じました。
// 問合せ方法は https://github.com/oss-gate/members と同じように /contacts というissueでやると良いかも
// 学内は1つ出来ると良いなぁと思うのですが、さらにハードルが高そう (実施主体が学生なら継続が難しいし、先生でも忙しすぎて出来無さそう)

というところで、ページに載せる上でも、企業の背景は聞きたいところです。
改めて、その企業さんにお邪魔してお話聞く or 質問を投げかけること (@satoryu さんに挙げて頂いた3つの質問) が出来るとうれしいですのですが、どうでしょうか? > @kou

**Comment by y-goto** [comment]
あらかじめOSSを決めておいて事前に手続きしておくとか、色々やり方はあると思うので、機会があったらまた弊社内でOSS Gateができないか考えてみたいですけどね。中にはOSSについてわかってくれる人もいますからね。

あと、私も企業の背景について伺うのは大賛成です。考え方とかはほかの企業にも参考になるはずです。

**Comment by kou** [comment]
「（調べればわかるだろうけど）企業名を明記しないようにするのでレポートだしますね」と言ってレポートを書いた経緯があるので、これから追加でどうこうというのは話しにくいです。ごめんなさい。

> * なぜワークショップをお願いしたか（企業内の背景）

私が「やりませんか？」と言ったからです。

社内の開発者がOSSの開発に参加するとよいと企業が考えている理由は、技術力アップ・アップストリームで直したり改良したりする方がトータルでメンテナンスコストが安い・社外へのアピールといった感じです。OSSを使っていればわかってくる合理的な理由で、目新しい理由ではないと思います。OSS Gateに参加している人も含めて、こう思っている人は多いんじゃないかと思います。

> * ワークショップ当日の雰囲気（ビギナー視点）

リポジトリーにあるアンケート結果でなんとかしてもらえないでしょうか？
https://github.com/oss-gate/workshop/tree/master/tutorial/retrospectives/2016-06-11

> * ワークショップ後に企業内に起きたこと（変わったことやわかった課題など）

これはごめんなさい。

**Comment by satoryu** [comment]
開催の背景について理解しました。たしかに追加で聞きづらいですね 😅 

> OSSを使っていればわかってくる合理的な理由で、目新しい理由ではないと思います。

「OSSを使っていればわかってくる合理的な理由」を求めている企業が1社あるということがわかったのは収穫ではないかと思います。 恐らく潜在的にも同様な企業があるのではないかと。

> リポジトリーにあるアンケート結果でなんとかしてもらえないでしょうか？
https://github.com/oss-gate/workshop/tree/master/tutorial/retrospectives/2016-06-11

これは失念してました。読みますー

> > * ワークショップ後に企業内に起きたこと（変わったことやわかった課題など）
> 
> これはごめんなさい。

今回は仕方がないですね。

一回目の出張版、お疲れ様でした！

**Comment by sezemiadmin** [comment]
了解しましたー。それなら嚴しいですね。
では、問合せがあることを願って、2回目のときに考えましょう。
あとは、また私が営業の合間で、興味ありそうな企業や先生がいれば、声かけてみます!
引きがあれば、またチャットルームで、また相談させてください

**Comment by kou** [comment]
企業さんがレポートを公開していました！
http://technica-blog.jp/entry/2016/06/24/185427
