### ISSUE TITLE
2016-09-24 東京レポート

### ISSUE THREAD

**Issue by ycatch** [oss-gate/oss-gate.github.io#7]
レポータとして参加したので、2016-09-24 東京のレポートを準備中です。
一応、Isuueを立てます。

1) 今回の記事のライセンスは、[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)
にする予定ですが、不都合があれば教えてください。

2) 記事は、oss-gate.github.io\_posts に、mdファイルをアップ

3) 写真は、oss-gate.github.io/images/20160924/ です。

**Comment by kou** [comment]
> 1) 今回の記事のライセンスは、CC BY 4.0
> にする予定ですが、不都合があれば教えてください。

まったく問題ありません！ずっと自由に利用できるライセンスなので適切だと思います！

> 2) 記事は、oss-gate.github.io_posts に、mdファイルをアップ
> 
> 3) 写真は、oss-gate.github.io/images/20160924/ です。

いいと思います。

**Comment by ycatch** [comment]
kou さん。
コメントありがとうございました。

typoの指摘なども対応しましたので、問題なければマージしていただけるとウレシイです。
よろしくお願いします。

**Comment by kou** [comment]
マージしたので公開されました！ http://oss-gate.github.io/report/workshop/2016/09/24/workshop-report-tokyo.html

いくつか間違いがあったので直しておきました！
https://github.com/oss-gate/oss-gate.github.io/compare/c36276048679bedfe66e98f8c9fcf751570aac9f...1f01ce9ba2e68a517e35aeadbfae764c3e531894

**Comment by ycatch** [comment]
kou さん。

マージ＆修正ありがとうございました！
無事に公開されて、良かったです。
