### ISSUE TITLE
シェアボタンを記事に追加

### ISSUE THREAD

**Issue by piroor** [oss-gate/oss-gate.github.io#9]
https://oss-gate.github.io/report/workshop/2016/09/24/workshop-report-tokyo.html をTwitter等で紹介しようとして、そのようなボタン類が無い事に気がつきました。
タイトル付きでTweetするなどのボタンがあると、より紹介しやすくなってよいと思います。

**Comment by piroor** [comment]
ボタン用のコードを生成してくれるサービス（？）としては、

http://comtopia.jp/sns_btn/
https://syncer.jp/how-to-setting-share-button

などがあるようです。

**Comment by piroor** [comment]
Facebookなど「アプリ用のAPIキー」の取得が必要な物もあるようなので、勝手に取って追加してPRしてというわけにはいかないかも……

**Comment by tSU-RooT** [comment]
とりあえずTwitter用のボタンを設置するのはいいと思います。

**Comment by kou** [comment]
Twitterボタンがついたので閉じます。ｍ
