### ISSUE TITLE
LICENSEファイルがない

### ISSUE THREAD

**Issue by duck-0604** [oss-gate/oss-gate.github.io#99]
LICENSEファイルがないためライセンスの確認ができません。

**Comment by kou** [comment]
あれ、ホントですね。
CC BY-SA 4.0のつもりでした！（本当はCC BY-SA 4.0 or laterにしたいけどそういう表記はできなかった気がする。）
（Creative Commonsは https://opensource.org/licenses/alphabetical に載っていないのでオープンソースではない。）

著作者はどうしようかしら。具体的に誰というのが曖昧になっちゃうけど「OSS Gate」でいいかしら。それとも、[Contributors](https://github.com/oss-gate/oss-gate.github.io/graphs/contributors)全員がいいかしら。

個人的には「OSS Gate」でいい気がするけど、どうかしら。

**Comment by knokmki612** [comment]
> 体的に誰というのが曖昧になっちゃうけど「OSS Gate」でいいかしら。

自分は異存ないです

**Comment by tdtds** [comment]
個人名でないと著作権保護期間が死後70年ではなく公表後70年になります:grin:
(もちろんそれで問題ないので「OSS Gate」で良いと思います)

**Comment by kou** [comment]
では、CC BY-SA 4.0で著作者はOSS Gateにしましょう。

トップレベルにLICENSEファイルを作って、README.mdと`_include/footerhtml`にライセンスのことを追記すれば十分なはず。

**Comment by kou** [comment]
Done by #99.
